"""``ks retry`` keeps the head an approval was taken on and judges it with no engineer (#646).

An approval covers only the diff it was taken on (#646 slice 2), and ``ks
retry`` used to delete the failed branch, so the engineer wrote the change
again and any regenerated byte made the approval miss. A size finding names
the line count, so a stand-in that writes one line more on each attempt
could never be let through by an approval.

``ks retry`` now keeps the failed branch when Phase 1 failed on waivable
checks alone and an approved item was taken on its tip. The factory lets
that one branch through its stale-branch preflight, skips the engineer once,
records the skip, and judges the kept commit. Anything else is regenerated,
with the reason printed.

Every test drives the real ``ks`` CLI in a subprocess with the harness of
``tests/test_inbox_waivers.py``: ``ks factory``, ``ks inbox approve`` or
``reject``, then ``ks retry``, on a real git repository with a bare origin
and a stub ``gh``. The engineer counts its own runs in a file.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from kstrl.inbox import ItemKind
from kstrl.manifest import Manifest
from tests.helpers import gitrepo
from tests.test_inbox_waiver_change import DEP, DEP_BRANCH, SIZE_TOML, _sha
from tests.test_inbox_waivers import (
    BRANCH,
    COMP,
    KEY_A,
    SECRET_TOML,
    _component,
    _decide,
    _env,
    _factory,
    _gated,
    _manifest_path,
    _open,
    _repo,
    _retry,
)

#: A size cap of five plus a denied path.
SIZE_AND_PATH_TOML = (
    '[policy]\nenabled = true\npaths_deny = ["secrets/**"]\nmax_lines_changed = 5\n'
)
#: Attempt n writes 9 + n lines, so no two attempts raise the same size finding.
GROWING = "mkdir -p app && seq 1 $((9 + n)) > app/big.txt"
#: Attempt n writes the same key under the variable KEY_n, so no two attempts
#: write the same diff.
RENAMED_SECRET = f'mkdir -p app && printf \'KEY_%s = "%s"\\n\' "$n" {KEY_A} > app/cfg.py'


def _counted(counter: Path, change: str) -> str:
    """A one-iteration engineer that counts its runs in ``counter``, makes ``change``
    (which may read the run number as ``$n``) and commits it."""
    return (
        f'n=$(( $(cat "{counter}" 2>/dev/null || echo 0) + 1 )); echo "$n" > "{counter}"; '
        f"{change} && git add -A && git commit -q -m work >/dev/null 2>&1; "
        "echo '<promise>COMPLETE</promise>'"
    )


def _runs(counter: Path) -> int:
    return int(counter.read_text(encoding="utf-8").strip())


def _events(root: Path) -> list[dict[str, object]]:
    """Every record of the latest run's events.jsonl."""
    run_id = Manifest.load(_manifest_path(root)).run_id
    path = root / ".kstrl" / "runs" / run_id / "events.jsonl"
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines()]


def _engineer_events(root: Path) -> list[str]:
    """The event names the latest run wrote for the engineer phase, in order."""
    return [
        str(record["event"])
        for record in _events(root)
        if isinstance(record.get("data"), dict)
        and record["data"].get("phase") == "engineer"  # type: ignore[union-attr]
        and str(record["event"]).startswith("phase_")
    ]


def _size_item(root: Path, lines: int) -> str:
    """The id of the open size item whose finding counts ``lines`` lines."""
    (item,) = [
        i
        for i in _open(root, ItemKind.POLICY_EXCEPTION)
        if i.evidence["explanation"].startswith(f"Too many lines changed: {lines} >")
    ]
    return item.id


def test_retry_keeps_the_approved_head_and_judges_it_without_an_engineer(tmp_path: Path) -> None:
    """Acceptance 1 (size): before #646 slice 3 the retry deleted the branch, the
    engineer wrote 11 lines, and the approval of the 10-line change was refused."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SIZE_TOML)
    env = _env(tmp_path, _counted(counter, GROWING))
    code, out = _factory(root, env)
    assert code == 1, out
    head = _sha(root, BRANCH)
    item = _size_item(root, 10)
    _decide(root, env, "approve", item)

    code, out = _retry(root, env)

    assert code == 0, out
    assert _runs(counter) == 1, out
    assert f"Kept branch '{BRANCH}' at {head[:12]}: approval {item[:8]}" in out, out
    assert _component(root).status == "completed", out
    assert _engineer_events(root) == ["phase_skipped"], _engineer_events(root)
    (finding,) = _gated(root, "policy_")
    assert (finding.severity, f"waiver:{item}" in finding.tags) == ("advisory", True)
    gh_log = (tmp_path / "gh.log").read_text(encoding="utf-8")
    assert f"waived by inbox approval {item[:8]}" in gh_log, gh_log


def test_retry_keeps_an_approved_secret_head_the_engineer_would_rename(tmp_path: Path) -> None:
    """Acceptance 1 (secret): attempt n writes the key as KEY_n. An approval
    covers only the diff it was taken on, so a regenerated change would be
    asked again. The retry keeps the approved head instead, with no engineer."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SECRET_TOML)
    env = _env(tmp_path, _counted(counter, RENAMED_SECRET))
    code, out = _factory(root, env)
    assert code == 1, out
    assert _component(root).failed_check == "policy_envelope", out
    head = _sha(root, BRANCH)
    (item,) = _open(root, ItemKind.POLICY_EXCEPTION)
    assert item.evidence["category"] == "policy_secret_pattern", item.evidence
    _decide(root, env, "approve", item.id)

    code, out = _retry(root, env)

    assert code == 0, out
    assert _runs(counter) == 1, out
    assert f"Kept branch '{BRANCH}' at {head[:12]}: approval {item.id[:8]}" in out, out
    assert _component(root).status == "completed", out
    assert _engineer_events(root) == ["phase_skipped"], _engineer_events(root)
    (finding,) = _gated(root, "policy_")
    assert (finding.category, finding.severity) == ("policy_secret_pattern", "advisory")
    assert f"waiver:{item.id}" in finding.tags, finding
    gh_log = (tmp_path / "gh.log").read_text(encoding="utf-8")
    assert f"waived by inbox approval {item.id[:8]}" in gh_log, gh_log


def test_a_kept_head_still_fails_on_a_finding_no_approval_covers(tmp_path: Path) -> None:
    """Acceptance 2 on one head: the size finding is approved, the denied path is not."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SIZE_AND_PATH_TOML)
    env = _env(tmp_path, _counted(counter, f"{GROWING} && mkdir -p secrets && echo k > secrets/k"))
    code, out = _factory(root, env)
    assert code == 1, out
    items = {i.evidence["category"]: i.id for i in _open(root, ItemKind.POLICY_EXCEPTION)}
    assert set(items) == {"policy_max_lines_changed", "policy_paths_deny"}, items
    _decide(root, env, "approve", items["policy_max_lines_changed"])

    code, out = _retry(root, env)

    assert code == 1, out
    assert _runs(counter) == 1, out
    assert "Kept branch" in out, out
    severities = {f.category: f.severity for f in _gated(root, "policy_")}
    assert severities == {"policy_max_lines_changed": "advisory", "policy_paths_deny": "high"}
    # Read once: the failed re-judge leaves nothing that skips a later engineer.
    assert _component(root).rejudge_sha == "", _component(root)
    (still_open,) = _open(root, ItemKind.POLICY_EXCEPTION)
    assert still_open.id == items["policy_paths_deny"], still_open

    _decide(root, env, "approve", items["policy_paths_deny"])
    code, out = _retry(root, env)

    assert code == 0, out
    assert _runs(counter) == 1, out
    assert _component(root).status == "completed", out


def test_an_approval_an_in_run_retry_superseded_keeps_nothing(tmp_path: Path) -> None:
    """Acceptance 2 on a regenerated change: the approved item was taken on
    attempt 1, and the branch tip is attempt 2's. The retry regenerates, and
    each new finding files its own item."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SIZE_TOML)
    env = _env(tmp_path, _counted(counter, GROWING))
    code, out = _factory(root, env, "--max-retries", "1")
    assert code == 1, out
    tip = _sha(root, BRANCH)
    first = _size_item(root, 10)
    _decide(root, env, "approve", first)

    code, out = _retry(root, env)

    assert code == 1, out
    assert f"no approved item was taken on commit {tip[:12]}, the branch tip" in out, out
    assert "Kept branch" not in out, out
    assert _runs(counter) == 4, out
    (finding,) = _gated(root, "policy_")
    assert f"waiver_refused:{first}" in finding.tags, finding
    lines = {
        i.evidence["explanation"].split(" > ")[0] for i in _open(root, ItemKind.POLICY_EXCEPTION)
    }
    assert {"Too many lines changed: 12", "Too many lines changed: 13"} <= lines, lines


def test_an_approval_then_a_rejection_keeps_nothing(tmp_path: Path) -> None:
    """Acceptance 3: the rejected item is no approval, so the branch is regenerated."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SIZE_TOML)
    env = _env(tmp_path, _counted(counter, GROWING))
    code, out = _factory(root, env)
    assert code == 1, out
    item = _size_item(root, 10)
    _decide(root, env, "approve", item)
    _decide(root, env, "reject", item)

    code, out = _retry(root, env)

    assert code == 1, out
    assert f"Deleted branch '{BRANCH}'" in out, out
    assert _runs(counter) == 2, out
    assert _size_item(root, 11), out


def test_a_failure_an_approval_cannot_cover_regenerates(tmp_path: Path) -> None:
    """Phase 1 also failed on the tests, which no approval covers."""
    counter = tmp_path / "counter"
    root = _repo(
        tmp_path,
        SIZE_TOML,
        {"tests": "test ! -e app/broken", "typecheck": "true", "lint": "true"},
    )
    env = _env(tmp_path, _counted(counter, f"{GROWING} && touch app/broken"))
    code, out = _factory(root, env)
    assert code == 1, out
    _decide(root, env, "approve", _size_item(root, 10))

    code, out = _retry(root, env)

    assert code == 1, out
    assert "Phase 1 also failed on stack:tests, which no approval covers" in out, out
    assert _runs(counter) == 2, out


def test_a_branch_moved_after_the_approval_is_not_kept(tmp_path: Path) -> None:
    """A commit added by hand after the approval: the tip is not the approved commit."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SIZE_TOML)
    env = _env(tmp_path, _counted(counter, GROWING))
    code, out = _factory(root, env)
    assert code == 1, out
    _decide(root, env, "approve", _size_item(root, 10))
    gitrepo.git_in(root, "checkout", "-q", BRANCH)
    gitrepo.git_in(root, "commit", "-q", "--allow-empty", "-m", "by hand")
    gitrepo.git_in(root, "checkout", "-q", "main")
    moved = _sha(root, BRANCH)

    code, out = _retry(root, env)

    assert f"no approved item was taken on commit {moved[:12]}, the branch tip" in out, out
    assert _runs(counter) == 2, out


def test_a_component_judged_with_unmerged_dependency_code_is_not_kept(tmp_path: Path) -> None:
    """Under --no-prs a completed dependency's code reaches the component only
    through its branch, so the component was judged from the commit it started
    at. Owner decision 4a: such a component is regenerated, with the reason."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SIZE_TOML)
    feature = root / "scripts" / "kstrl" / "feature"
    prd = json.loads((feature / COMP / "prd.json").read_text(encoding="utf-8"))
    (feature / DEP).mkdir()
    (feature / DEP / "prd.json").write_text(
        json.dumps({**prd, "branchName": DEP_BRANCH}), encoding="utf-8"
    )
    gitrepo.git_in(root, "add", "-A")
    gitrepo.git_in(root, "commit", "-q", "-m", "dependency prd")
    gitrepo.git_in(root, "push", "-q", "origin", "main")
    manifest = json.loads(_manifest_path(root).read_text(encoding="utf-8"))
    (comp,) = manifest["components"]
    dep = {**comp, "id": DEP, "title": DEP, "branchName": DEP_BRANCH}
    dep["prdPath"] = f"scripts/kstrl/feature/{DEP}/prd.json"
    manifest["components"] = [dep, {**comp, "dependencies": [DEP]}]
    _manifest_path(root).write_text(json.dumps(manifest), encoding="utf-8")
    env = _env(
        tmp_path,
        'case "$(basename "$PWD")" in a) printf "a\\n" > a.txt && git add -A && '
        "git commit -q -m a >/dev/null 2>&1; echo '<promise>COMPLETE</promise>';; "
        f"*) {_counted(counter, GROWING)};; esac",
    )
    code, out = _factory(root, env, "--no-prs")
    assert code == 1, out
    _decide(root, env, "approve", _size_item(root, 10))

    code, out = _retry(root, env)

    assert f"it was judged with unmerged dependency code from {DEP_BRANCH}" in out, out
    assert f"Deleted branch '{BRANCH}'" in out, out
    assert _runs(counter) == 2, out


@pytest.mark.parametrize("recorded", ["main", "not-a-commit"])
def test_a_run_refuses_a_kept_branch_that_is_not_at_the_kept_commit(
    tmp_path: Path, recorded: str
) -> None:
    """The factory lets a kept branch through its stale-branch preflight only
    at the commit ``ks retry`` kept. A manifest naming another commit (here
    main's), or a value that is no commit at all, is refused before any
    engineer runs."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SIZE_TOML)
    env = _env(tmp_path, _counted(counter, GROWING))
    code, out = _factory(root, env)
    assert code == 1, out
    value = _sha(root, "main") if recorded == "main" else recorded
    manifest = json.loads(_manifest_path(root).read_text(encoding="utf-8"))
    (comp,) = manifest["components"]
    manifest["components"] = [{**comp, "status": "pending", "rejudgeSha": value}]
    _manifest_path(root).write_text(json.dumps(manifest), encoding="utf-8")

    code, out = _factory(root, env)

    assert code == 2, out
    assert _runs(counter) == 1, out
    if recorded == "main":
        assert f"and ks retry kept it at {value[:12]}" in out, out
    else:
        assert "rejudgeSha: must be" in out, out


def test_a_single_pr_component_is_regenerated_not_kept(tmp_path: Path) -> None:
    """Owner decision 4a: a single_pr component is never kept, and the plan says
    why. The shared branch carries other components' commits, so its tip is not
    one component's judged change."""
    counter = tmp_path / "counter"
    root = _repo(tmp_path, SIZE_TOML)
    manifest = json.loads(_manifest_path(root).read_text(encoding="utf-8"))
    _manifest_path(root).write_text(json.dumps({**manifest, "singlePr": True}), encoding="utf-8")
    env = _env(tmp_path, _counted(counter, GROWING))
    code, out = _factory(root, env)
    assert code == 1, out
    _decide(root, env, "approve", _size_item(root, 10))

    code, out = _retry(root, env)

    assert "single_pr: the shared branch carries other components' commits" in out, out
    assert "Kept branch" not in out, out
    assert _component(root).rejudge_sha == "", out
