"""The bodies of the pull requests kstrl opens (#639 slice 5 split them out of
``kstrl/pr.py``, which creates and merges them)."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING

from kstrl.acceptance_lines import pr_section
from kstrl.findings import (
    CLAIM_DISAGREEMENT_CATEGORY,
    finding_waiver,
    render_findings_markdown,
)
from kstrl.prd import PRD
from kstrl.requirements import built_by
from kstrl.statedir import pre_run_prd_path

if TYPE_CHECKING:
    from kstrl.manifest import Component, Manifest
    from kstrl.requirements import SpecRequirement

#: The line every PR body kstrl writes ends with. Hoisted to a constant
#: so the readers that identify a kstrl-authored PR by it - the R10.7
#: open-PR bound, the baseline, the polled steering channel (#231) -
#: cannot drift apart from the two sites that write it.
PR_FOOTER_MARKER = "Generated by [kstrl](https://github.com/0xfauzi/kstrl)"


def requirements_section(
    requirements: Sequence[SpecRequirement], root: Path, components: Sequence[Component]
) -> list[str]:
    """The ``## Requirements`` section: the id and statement of each
    requirement a story of ``components`` builds (#639 slice 5), or []
    when the run bound none. The story ids are read from the PRD each
    component started from, the copy the plan gate approved."""
    if not requirements:
        return []
    story_ids: set[str] = set()
    for comp in components:
        path = pre_run_prd_path(root, comp.id, comp.prd_path, plan_id=comp.plan_id)
        try:
            story_ids.update(story.id for story in PRD.load(path).user_stories)
        except (OSError, ValueError) as exc:
            told = f"The requirements this change builds cannot be named: {path}: {exc}"
            return ["## Requirements", "", told, ""]
    built = [f"- {r.id}: {r.statement}" for r in built_by(requirements, story_ids)]
    return ["## Requirements", "", *(built or ["No requirement names a story of this change."]), ""]


def component_pr_body(
    component: Component,
    manifest: Manifest,
    root: Path,
    *,
    isolation: str,
    requirements: Sequence[SpecRequirement],
) -> str:
    """Generate a PR description for a component. ``root`` reads the run's
    acceptance record into a ``## Acceptance`` section (#700 slice 4) and
    the component's PRD into a ``## Requirements`` section (#639 slice 5)."""
    lines: list[str] = []

    lines.append("## Summary")
    lines.append("")
    lines.append(component.description)
    lines.append("")

    # Dependencies
    if component.dependencies:
        lines.append("## Dependencies")
        lines.append("")
        for dep_id in component.dependencies:
            dep = manifest.get_component(dep_id)
            if dep and dep.pr_url:
                lines.append(f"- [{dep.title}]({dep.pr_url})")
            elif dep:
                lines.append(f"- {dep.title} (`{dep_id}`)")
            else:
                lines.append(f"- `{dep_id}`")
        lines.append("")

    # Review findings (if any). The string at component.review_findings
    # is the canonical human-readable PR-body content because it carries
    # information the typed Finding stream does not: PASS criteria
    # confirmations, criterion-level pass/fail/advisory counts, and the
    # criterion text as headers (Finding.category is "prd_criterion" for
    # all of them, which obscures what the criterion actually asserted).
    # The typed component.findings is still load-bearing -- it ships to
    # the evolution journal via record_run for dashboards and
    # aggregations -- but pr.py is the wrong consumer for it.
    # render_findings_markdown remains available for ad-hoc dumping.
    if component.review_findings:
        lines.append(component.review_findings)
        lines.append("")

    # R1.2 (sec-pr-body): phases that never executed must be visible in
    # the PR body. In advisory mode a security infrastructure error used
    # to produce NO security section at all - "did not run" was
    # indistinguishable from "ran clean". Render the existing
    # render_findings_markdown callouts for exactly the non-execution
    # subset (infra errors + deliberate skips); real findings stay with
    # the richer review_findings string above.
    #
    # R10.3 adds claim disagreements to the same callout set, for
    # the opposite reason to the one that keeps criteria out of it. A
    # criterion finding is excluded because its category is always
    # "prd_criterion", which says less than the string above already
    # does. A claim finding has a category that means something and
    # carries the story id in `location`, and the review_findings string
    # cannot carry it at all: it renders criteria and concerns, and this
    # is neither. Without this it would reach the manifest and the
    # journal and be invisible on the pull request, which for an
    # advisory-only gate is the same as not existing.
    #
    # #696 decision 7: Phase 1 records Layer 0 as not measured from level 1
    # as a phase skip, so this callout is where the pull request says so.
    callouts = [
        f
        for f in component.findings
        if f.is_infrastructure_error
        or f.is_phase_skip
        or f.category == CLAIM_DISAGREEMENT_CATEGORY
        # #595: a finding an inbox approval waived is on the PR, naming it.
        or finding_waiver(f) is not None
    ]
    if callouts:
        lines.append(render_findings_markdown(callouts).rstrip())
        lines.append("")

    lines.extend(requirements_section(requirements, root, [component]))
    lines.extend(["## Isolation", "", isolation, ""])  # #700: the label the checks ran under
    lines.extend(pr_section(root, manifest.run_id, component.id))

    # PRD reference
    lines.append("## PRD")
    lines.append("")
    lines.append(f"- File: `{component.prd_path}`")
    lines.append(f"- Component: `{component.id}`")
    lines.append("")

    # R7.4: Linear magic-word trailer. "Fixes EXC-42" makes Linear's
    # GitHub integration move the issue to Done when this PR merges -
    # status transitions cost kstrl zero API calls.
    if component.linear_issue_identifier:
        lines.append(f"Fixes {component.linear_issue_identifier}")
        lines.append("")

    lines.append("---")
    lines.append(PR_FOOTER_MARKER)

    return "\n".join(lines)


def single_pr_body(
    manifest: Manifest, root: Path, *, isolation: str, requirements: Sequence[SpecRequirement]
) -> str:
    """The body of the one PR ``--single-pr`` opens for every completed component."""
    lines: list[str] = []
    lines.append("## Summary")
    lines.append("")
    # #639: a pinned plan names the exact spec text it was made from.
    spec = (
        f"`{manifest.spec_path}` (sha256 {manifest.spec_digest[:12]})"
        if manifest.spec_digest
        else f"`{manifest.spec_file}`"
    )
    lines.append(f"Factory run for **{manifest.project_name}** from {spec}.")
    lines.append("")
    lines.append("## Components")
    lines.append("")

    for comp in manifest.components:
        status = "completed" if comp.status == "completed" else comp.status
        lines.append(f"- **{comp.title}** (`{comp.id}`): {status}")
        if comp.description:
            lines.append(f"  {comp.description}")

    lines.append("")
    completed = [comp for comp in manifest.components if comp.status == "completed"]
    lines.extend(requirements_section(requirements, root, completed))
    lines.extend(["## Isolation", "", isolation, ""])  # #700: the label the checks ran under
    lines.append("---")
    lines.append(PR_FOOTER_MARKER)
    return "\n".join(lines)
