#!/usr/bin/env python3
"""Generate the README CLI reference and config reference from code.

The README's two generated sections sit between marker comments:

    <!-- BEGIN GENERATED: cli-reference -->  ...  <!-- END GENERATED: cli-reference -->
    <!-- BEGIN GENERATED: config-reference --> ... <!-- END GENERATED: config-reference -->

Everything outside the markers is hand-written and untouched.

The CLI reference is introspected from the click command tree
(``ralph_py.cli:cli``), so a command that does not exist cannot be
documented and a new command cannot be silently omitted.

The config reference is verified behaviorally, not transcribed: for
every documented ``[section]`` key the script writes a sentinel value
into a throwaway ralph.toml, runs the real loader, and asserts the
resolved config changed. It also probes every *undocumented* dataclass
field name of the per-section configs and fails if one turns out to be
a live toml key. Defaults shown in the output come from the dataclass
default instances. A key that stops working, changes its default, or
gets added without documentation makes regeneration produce a diff (or
an error), which CI catches.

Usage:
    uv run python scripts/gen_docs.py            # rewrite README.md in place
    uv run python scripts/gen_docs.py --check    # exit 1 if README.md is stale
"""

from __future__ import annotations

import argparse
import dataclasses
import os
import sys
import tempfile
from collections.abc import Callable, Iterator
from contextlib import contextmanager
from pathlib import Path
from typing import Any

import click

REPO_ROOT = Path(__file__).resolve().parent.parent
README_PATH = REPO_ROOT / "README.md"

GENERATED_NOTE = "<!-- Generated by scripts/gen_docs.py - do not edit by hand. -->"


def _marker(name: str, end: bool = False) -> str:
    return f"<!-- {'END' if end else 'BEGIN'} GENERATED: {name} -->"


# ---------------------------------------------------------------------------
# CLI reference (click introspection)
# ---------------------------------------------------------------------------


def _iter_commands(
    group: click.Group, prefix: str,
) -> Iterator[tuple[str, click.Command]]:
    """Yield (full command path, command) for every leaf command, depth-first."""
    for name in sorted(group.commands):
        cmd = group.commands[name]
        path = f"{prefix} {name}"
        if isinstance(cmd, click.Group):
            yield from _iter_commands(cmd, path)
        else:
            yield path, cmd


def _usage_suffix(cmd: click.Command, path: str) -> str:
    """Return the argument part of a command's usage line (no [OPTIONS])."""
    ctx = click.Context(cmd, info_name=path)
    pieces = [p for p in cmd.collect_usage_pieces(ctx) if p != "[OPTIONS]"]
    return (" " + " ".join(pieces)) if pieces else ""


def build_cli_reference() -> str:
    from ralph_py.cli import cli

    entries: list[tuple[str, str]] = []
    for path, cmd in _iter_commands(cli, "ralph"):
        invocation = f"{path}{_usage_suffix(cmd, path)}"
        entries.append((invocation, cmd.get_short_help_str(limit=120)))

    width = max(len(invocation) for invocation, _ in entries) + 2
    lines = [f"{invocation:<{width}}{help_text}" for invocation, help_text in entries]
    body = "\n".join(lines)
    return (
        f"{GENERATED_NOTE}\n\n"
        f"```\n{body}\n```\n\n"
        "Run `ralph COMMAND --help` for the full option list of any command.\n"
    )


# ---------------------------------------------------------------------------
# Config reference (dataclass defaults + behavioral toml-key probing)
# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class SectionSpec:
    """One documented ralph.toml section.

    ``keys`` maps toml key -> dataclass field name. ``loader`` is the
    real load(root_dir) classmethod, ``defaults`` the raw default
    instance whose field values are rendered as the documented defaults.
    """

    section: str
    title: str
    keys: dict[str, str]
    loader: Callable[[Path], Any]
    defaults: Any
    probe_undocumented_fields: bool


def _section_specs() -> list[SectionSpec]:
    from ralph_py.breaker import BreakerConfig
    from ralph_py.config import RalphConfig
    from ralph_py.contract import ContractConfig
    from ralph_py.evolution import EvolutionConfig
    from ralph_py.factory import FactoryConfig
    from ralph_py.feedforward import FeedforwardConfig
    from ralph_py.fixtures import FixturesConfig
    from ralph_py.knowledge import KnowledgeConfig
    from ralph_py.linear import LinearConfig
    from ralph_py.sandbox import SandboxConfig
    from ralph_py.security import SecurityConfig
    from ralph_py.timeout import TimeoutConfig
    from ralph_py.verify import VerifyConfig

    def ralph_loader(root: Path) -> Any:
        return RalphConfig.load(root_dir=root)

    ralph_defaults = RalphConfig()

    def identity_keys(cfg_cls: Any, names: list[str]) -> dict[str, str]:
        field_names = {f.name for f in dataclasses.fields(cfg_cls)}
        missing = set(names) - field_names
        if missing:
            raise SystemExit(
                f"gen_docs spec error: {cfg_cls.__name__} has no fields {sorted(missing)}"
            )
        return {n: n for n in names}

    specs = [
        # RalphConfig fans out over five sections with renamed keys; the
        # key->field mapping is declared here and verified behaviorally.
        SectionSpec(
            "agent", "Agent selection",
            {
                "type": "agent_type",
                "command": "agent_cmd",
                "model": "model",
                "reasoning_effort": "model_reasoning_effort",
            },
            ralph_loader, ralph_defaults, probe_undocumented_fields=False,
        ),
        SectionSpec(
            "run", "Loop behavior",
            {
                "max_iterations": "max_iterations",
                "sleep_seconds": "sleep_seconds",
                "interactive": "interactive",
            },
            ralph_loader, ralph_defaults, probe_undocumented_fields=False,
        ),
        SectionSpec(
            "paths", "File locations",
            {
                "prompt": "prompt_file",
                "prd": "prd_file",
                "progress": "progress_file",
                "codebase_map": "codebase_map_file",
                "allowed": "allowed_paths",
            },
            ralph_loader, ralph_defaults, probe_undocumented_fields=False,
        ),
        SectionSpec(
            "git", "Branch handling",
            {"branch": "ralph_branch", "auto_checkout": "auto_checkout"},
            ralph_loader, ralph_defaults, probe_undocumented_fields=False,
        ),
        SectionSpec(
            "ui", "Output rendering",
            {"ascii": "ascii_only"},
            ralph_loader, ralph_defaults, probe_undocumented_fields=False,
        ),
        SectionSpec(
            "timeout", "Timeout limits (seconds; 0 or less disables)",
            identity_keys(TimeoutConfig, [f.name for f in dataclasses.fields(TimeoutConfig)]),
            lambda root: TimeoutConfig.load(root_dir=root),
            TimeoutConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "factory", "Factory orchestration (Phase 0-3 pipeline)",
            identity_keys(FactoryConfig, [
                "max_parallel", "max_retries", "retry_delay", "use_worktrees",
                "single_pr", "create_prs", "review_mode", "merge_timeout",
                "max_adversarial_calls", "max_total_tokens",
                "pause_before_pr_merge", "progress_log_enabled",
                "keep_worktrees_on_failure",
            ]),
            lambda root: FactoryConfig.load(root_dir=root),
            FactoryConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "breaker",
            "No-progress circuit breaker (R7.5; 0 iterations disables)",
            identity_keys(BreakerConfig, [
                f.name for f in dataclasses.fields(BreakerConfig)
            ]),
            lambda root: BreakerConfig.load(root_dir=root),
            BreakerConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "sandbox",
            "OS-level agent sandboxing (R7.5; claude-code/codex only)",
            identity_keys(SandboxConfig, [
                f.name for f in dataclasses.fields(SandboxConfig)
            ]),
            lambda root: SandboxConfig.load(root_dir=root),
            SandboxConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "verify", "Phase 1 mechanical verification",
            identity_keys(VerifyConfig, [f.name for f in dataclasses.fields(VerifyConfig)]),
            lambda root: VerifyConfig.load(root_dir=root),
            VerifyConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "fixtures", "Phase 1 approved-fixtures oracle (R7.2; default off)",
            identity_keys(FixturesConfig, [
                f.name for f in dataclasses.fields(FixturesConfig)
            ]),
            lambda root: FixturesConfig.load(root_dir=root),
            FixturesConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "security", "Phase 2.5 security review",
            identity_keys(SecurityConfig, [f.name for f in dataclasses.fields(SecurityConfig)]),
            lambda root: SecurityConfig.load(root_dir=root),
            SecurityConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "contract", "Phase 3 cross-component contract testing",
            identity_keys(ContractConfig, [f.name for f in dataclasses.fields(ContractConfig)]),
            lambda root: ContractConfig.load(root_dir=root),
            ContractConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "feedforward", "Phase 0 feedforward (computational, no LLM)",
            identity_keys(
                FeedforwardConfig,
                [f.name for f in dataclasses.fields(FeedforwardConfig)],
            ),
            lambda root: FeedforwardConfig.load(root_dir=root),
            FeedforwardConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "knowledge", "Per-component knowledge layer",
            identity_keys(KnowledgeConfig, [
                "enabled", "max_core_tokens", "max_dependency_tokens",
                "max_sibling_tokens", "distill_timeout_seconds",
                "distill_model", "max_facts_per_distill", "dependency_scope",
            ]),
            lambda root: KnowledgeConfig.load(root_dir=root),
            KnowledgeConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "evolution", "Continuous-learning journal",
            identity_keys(EvolutionConfig, [f.name for f in dataclasses.fields(EvolutionConfig)]),
            lambda root: EvolutionConfig.load(root_dir=root),
            EvolutionConfig(), probe_undocumented_fields=True,
        ),
        SectionSpec(
            "linear", "Linear integration (R7.4; default off)",
            identity_keys(LinearConfig, [f.name for f in dataclasses.fields(LinearConfig)]),
            lambda root: LinearConfig.load(root_dir=root),
            LinearConfig(), probe_undocumented_fields=True,
        ),
    ]
    return specs


# One-line description per documented key. Regeneration fails when a key
# has no description, so new keys cannot land undocumented.
KEY_DESCRIPTIONS: dict[tuple[str, str], str] = {
    ("agent", "type"): '"claude" | "codex" | "custom"',
    ("agent", "command"): "shell command (only used when type = \"custom\")",
    ("agent", "model"): 'e.g. "sonnet" (claude) or "o3" (codex); empty = agent default',
    ("agent", "reasoning_effort"): "low | medium | high | max (model-dependent)",
    ("run", "max_iterations"): "iteration budget per component",
    ("run", "sleep_seconds"): "pause between iterations",
    ("run", "interactive"): "human-in-the-loop mode for the legacy loop",
    ("paths", "prompt"): "engineer prompt file",
    ("paths", "prd"): "PRD file",
    ("paths", "progress"): "progress log the agent appends to",
    ("paths", "codebase_map"): "brownfield codebase notes",
    ("paths", "allowed"): 'diff-scope allowlist, e.g. ["src/", "tests/"]; empty = unrestricted',
    ("git", "branch"): "branch override; empty = use PRD branchName",
    ("git", "auto_checkout"): "check the branch out automatically",
    ("ui", "ascii"): "ASCII separators only (no box-drawing characters)",
    ("timeout", "git_operation"): "per git subprocess",
    ("timeout", "agent_iteration"): "one engineer iteration",
    ("timeout", "component_total"): "wall clock per component across iterations",
    ("timeout", "verification_check"): "each Phase 1 check subprocess",
    ("timeout", "review_agent"): "Phase 2 reviewer call",
    ("timeout", "contract_test"): "Phase 3 contract test run",
    ("timeout", "subprocess_default"): "any other subprocess",
    ("timeout", "scheduler_backstop_margin"):
        "extra slack before the scheduler declares a worker dead",
    ("factory", "max_parallel"): "concurrent component workers",
    ("factory", "max_retries"): "per-component retry budget across all phases",
    ("factory", "retry_delay"): "seconds between retry attempts",
    ("factory", "use_worktrees"): "isolate each component in .ralph/worktrees/<id>",
    ("factory", "single_pr"): "one PR for the whole run instead of per-component",
    ("factory", "create_prs"): "push + merge PRs via gh",
    ("factory", "review_mode"): "hard | advisory | skip (Phase 2)",
    ("factory", "merge_timeout"): "seconds to wait for PR merge confirmation",
    ("factory", "max_adversarial_calls"): "cap on review+security+distill LLM calls; 0 = unbounded",
    ("factory", "max_total_tokens"): "run-level token budget; 0 = unbounded",
    ("factory", "pause_before_pr_merge"): "human checkpoint before each PR (E6)",
    ("factory", "progress_log_enabled"):
        "JSONL event log at .ralph/progress.jsonl (R3.2)",
    ("factory", "keep_worktrees_on_failure"):
        "keep failed components' worktrees for post-mortem (R3.3)",
    ("breaker", "no_progress_iterations"):
        "halt after N consecutive no-progress iterations; 0 disables (R7.5)",
    ("breaker", "test_command"):
        "stall-probe command; empty = the explicit [verify] test_command, "
        "else diff-hash only",
    ("breaker", "test_timeout"): "seconds before the stall probe is killed",
    ("sandbox", "enabled"):
        "OS-sandbox the engineer's agent CLI (writes scoped to its "
        "worktree); ignored for custom agent commands",
    ("sandbox", "allow_network"):
        "re-open outbound network inside the sandbox (off = deny)",
    ("verify", "test_command"): "empty = smart default (uv run pytest)",
    ("verify", "typecheck_command"): "empty = smart default (uv run mypy)",
    ("verify", "lint_command"): "empty = smart default (uv run ruff check)",
    ("verify", "check_diff_scope"): "fail on changes outside allowed paths",
    ("verify", "check_bad_patterns"): "scan the diff for secret-like patterns",
    ("verify", "dead_code_cleanup"): "optional dead-code check",
    ("verify", "dead_code_command"): "empty = smart default when dead_code_cleanup is on",
    ("verify", "mutation_testing"): "optional mutation testing",
    ("verify", "mutation_threshold"): "minimum mutation kill rate (percent)",
    ("verify", "mutation_timeout"): "seconds for the mutation run",
    ("verify", "subprocess_timeout"): "seconds per verification subprocess",
    ("verify", "require_self_critique"):
        "fail Phase 1 if the ## Self-Critique block is missing/sparse",
    ("verify", "self_critique_min_bullets"): "minimum substantive bullets in the block",
    ("verify", "progress_file_path"): "progress file the self-critique check reads",
    ("fixtures", "enabled"):
        "run PRD-defined fixtures during Phase 1 (sandboxed; opt-in)",
    ("fixtures", "snapshot_on_success"):
        "save passing outputs for cross-run regression comparison",
    ("fixtures", "snapshot_dir"): "relative paths resolve against the repo root",
    ("fixtures", "timeout"): "seconds per fixture subprocess",
    ("security", "mode"): "skip | advisory | hard",
    ("security", "agent_cmd"): "empty = inherit [agent]",
    ("security", "agent_type"): "empty = inherit [agent]",
    ("security", "model"): "empty = inherit [agent]",
    ("security", "timeout_seconds"): "reviewer call timeout",
    ("security", "fail_threshold"): "critical | high | medium | low (hard mode)",
    ("contract", "mode"): "tier | final | skip",
    ("contract", "test_command"): "integration test command on merged tiers",
    ("contract", "timeout"): "seconds per contract test run",
    ("feedforward", "enabled"): "inject structural context into the prompt",
    ("feedforward", "module_map"): "directory tree with LOC counts",
    ("feedforward", "public_interfaces"): "public symbols via Python ast",
    ("feedforward", "dependency_graph"): "internal import analysis (Python only)",
    ("feedforward", "conventions"): "extract from pyproject.toml, ruff.toml, ...",
    ("feedforward", "max_context_tokens"): "cap to avoid prompt bloat",
    ("knowledge", "enabled"): "distill + inject durable facts",
    ("knowledge", "max_core_tokens"): "current component's facts (full text)",
    ("knowledge", "max_dependency_tokens"): "dependency facts (full text)",
    ("knowledge", "max_sibling_tokens"): "other components' facts (first sentence)",
    ("knowledge", "distill_timeout_seconds"): "distiller call timeout",
    ("knowledge", "distill_model"): "empty = falls back to [agent].model",
    ("knowledge", "max_facts_per_distill"): "cap on facts written per component",
    ("knowledge", "dependency_scope"): "direct | transitive (E8)",
    ("evolution", "enabled"): "record run outcomes",
    ("evolution", "journal_path"): "JSONL journal location",
    ("evolution", "experiments_path"): "experiment tracker location",
    ("evolution", "min_pattern_frequency"): "pattern must recur N times before proposal",
    ("evolution", "lookback_runs"): "past runs to analyze",
    ("evolution", "auto_propose"): "generate proposals after each factory run",
    ("evolution", "auto_apply_computational"): "auto-apply computational proposals",
    ("linear", "enabled"): "mirror runs into Linear (project/issues/status via GitHub linking)",
    ("linear", "team_id"): "Linear team UUID (required when enabled)",
    ("linear", "token_env"): "NAME of the env var holding the API token",
    ("linear", "auth_mode"): "auto | api_key | oauth (auto sniffs the lin_api_ prefix)",
    ("linear", "api_url"): "GraphQL endpoint",
    ("linear", "dry_run"): "record mutations instead of sending them",
    ("linear", "timeout_seconds"): "per-request timeout",
    ("linear", "min_request_interval"): "client-side throttle between requests (seconds)",
}

# Sentinel values for keys whose loader validates against an enum; the
# generic type-derived sentinel would be rejected.
ENUM_SENTINELS: dict[tuple[str, str], str] = {
    ("agent", "type"): "codex",
    ("agent", "reasoning_effort"): "high",
    ("factory", "review_mode"): "advisory",
    ("security", "mode"): "hard",
    ("security", "fail_threshold"): "low",
    ("contract", "mode"): "final",
    ("knowledge", "dependency_scope"): "transitive",
    ("linear", "auth_mode"): "oauth",
}


def _sentinel_for(section: str, key: str, default: Any) -> Any:
    if (section, key) in ENUM_SENTINELS:
        return ENUM_SENTINELS[(section, key)]
    if isinstance(default, bool):
        return not default
    if isinstance(default, int):
        return default + 7919
    if isinstance(default, float):
        return default + 1234.5
    if isinstance(default, list):
        return ["sentinel/path/"]
    # str, Path, or None (str-shaped in toml)
    return "sentinel-value"


def _toml_literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, list):
        return "[" + ", ".join(_toml_literal(v) for v in value) + "]"
    if value is None:
        return '""'
    if isinstance(value, Path):
        return f'"{value.as_posix()}"'
    return f'"{value}"'


@contextmanager
def _scrubbed_environ() -> Iterator[None]:
    """Run with an empty-ish environment so a developer's RALPH_* / MODEL /
    NO_COLOR etc. cannot leak into the probed loaders (env beats toml)."""
    saved = dict(os.environ)
    keep = {"PATH", "HOME", "TMPDIR", "SystemRoot"}
    try:
        for name in list(os.environ):
            if name not in keep:
                del os.environ[name]
        yield
    finally:
        os.environ.clear()
        os.environ.update(saved)


def _write_probe_toml(path: Path, specs: list[SectionSpec], extra: dict[str, list[str]]) -> None:
    lines: list[str] = []
    for spec in specs:
        lines.append(f"[{spec.section}]")
        for key, field_name in spec.keys.items():
            default = getattr(spec.defaults, field_name)
            lines.append(f"{key} = {_toml_literal(_sentinel_for(spec.section, key, default))}")
        for key in extra.get(spec.section, ()):
            lines.append(f"{key} = {_toml_literal('sentinel-value')}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def _scalar_fields(defaults: Any) -> set[str]:
    names: set[str] = set()
    for f in dataclasses.fields(defaults):
        value = getattr(defaults, f.name)
        if value is None or isinstance(value, (bool, int, float, str, Path, list)):
            names.add(f.name)
    return names


def _verify_sections(specs: list[SectionSpec]) -> None:
    """Behavioral check: every documented key changes the resolved config;
    no undocumented scalar field of a per-section config is a live toml key."""
    errors: list[str] = []
    extra: dict[str, list[str]] = {}
    for spec in specs:
        if spec.probe_undocumented_fields:
            candidates = _scalar_fields(spec.defaults) - set(spec.keys.values())
            # None-defaulted non-scalar handling: only str-shaped probes are
            # meaningful; every current config field is scalar or a sub-config.
            extra[spec.section] = sorted(candidates)

    with _scrubbed_environ(), tempfile.TemporaryDirectory() as tmp:
        # Baseline and probe load from the SAME root, differing only in
        # whether ralph.toml exists: several configs resolve path fields
        # against root_dir, so loads from two different roots would
        # spuriously differ on fields the toml never touched.
        probe_root = Path(tmp) / "probe"
        probe_root.mkdir()
        toml_path = probe_root / "ralph.toml"

        baselines = {spec.section: spec.loader(probe_root) for spec in specs}
        _write_probe_toml(toml_path, specs, extra)

        for spec in specs:
            baseline = baselines[spec.section]
            probed = spec.loader(probe_root)
            for key, field_name in spec.keys.items():
                if getattr(probed, field_name) == getattr(baseline, field_name):
                    errors.append(
                        f"[{spec.section}] {key}: documented but setting it in "
                        f"ralph.toml did not change {type(baseline).__name__}.{field_name}"
                    )
            for field_name in extra.get(spec.section, ()):
                if getattr(probed, field_name) != getattr(baseline, field_name):
                    errors.append(
                        f"[{spec.section}] {field_name}: live toml key not documented "
                        "in scripts/gen_docs.py (add it to the section spec + description)"
                    )
            for key in spec.keys:
                if (spec.section, key) not in KEY_DESCRIPTIONS:
                    errors.append(f"[{spec.section}] {key}: missing KEY_DESCRIPTIONS entry")

    if errors:
        raise SystemExit("gen_docs config probing failed:\n  " + "\n  ".join(errors))


def build_config_reference() -> str:
    specs = _section_specs()
    _verify_sections(specs)

    blocks: list[str] = []
    for spec in specs:
        lines = [f"# {spec.title}", f"[{spec.section}]"]
        width = max(
            len(f"{key} = {_toml_literal(getattr(spec.defaults, field_name))}")
            for key, field_name in spec.keys.items()
        ) + 2
        for key, field_name in spec.keys.items():
            assignment = f"{key} = {_toml_literal(getattr(spec.defaults, field_name))}"
            description = KEY_DESCRIPTIONS[(spec.section, key)]
            lines.append(f"{assignment:<{width}}# {description}")
        blocks.append("\n".join(lines))

    body = "\n\n".join(blocks)
    return (
        f"{GENERATED_NOTE}\n"
        "<!-- Defaults come from the config dataclasses; every key is probed\n"
        "     against the real loaders before this section is emitted. -->\n\n"
        f"```toml\n{body}\n```\n\n"
        "Environment variables override ralph.toml, and CLI flags override both.\n"
        "See [docs/env-vars.md](docs/env-vars.md) for the full env-var mapping.\n"
    )


# ---------------------------------------------------------------------------
# README splicing
# ---------------------------------------------------------------------------


def _splice(text: str, name: str, generated: str) -> str:
    begin, end = _marker(name), _marker(name, end=True)
    if begin not in text or end not in text:
        raise SystemExit(f"README.md is missing the {begin} / {end} markers")
    head, rest = text.split(begin, 1)
    _, tail = rest.split(end, 1)
    return f"{head}{begin}\n{generated}{end}{tail}"


def render_readme(text: str) -> str:
    text = _splice(text, "cli-reference", build_cli_reference())
    text = _splice(text, "config-reference", build_config_reference())
    return text


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="verify README.md is current; exit 1 on drift without writing",
    )
    args = parser.parse_args(argv)

    current = README_PATH.read_text(encoding="utf-8")
    rendered = render_readme(current)

    if args.check:
        if rendered != current:
            sys.stderr.write(
                "README.md generated sections are stale.\n"
                "Run: uv run python scripts/gen_docs.py\n"
            )
            return 1
        print("README.md generated sections are current.")
        return 0

    if rendered != current:
        README_PATH.write_text(rendered, encoding="utf-8")
        print("README.md updated.")
    else:
        print("README.md already current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
